export const API_ENDPOINTS = {
  AUTH: {
    CHECK_PHONE: "/teachers/login",
    LOGIN_PASSWORD: "/teachers/login-password",
    VERIFY_OTP: "/teachers/verify-otp",
    SETUP_PASSWORD: "/teachers/setup-password",
    REGISTER: "/teachers/register",
    FORGOT_PASSWORD: "/teachers/forgot-password",
    VERIFY_FORGOT_PASSWORD: "/teachers/verify-forgot-password",
    RESET_PASSWORD: "/teachers/reset-password",
    PROFILE: "/teachers/profile",
    UPDATE_PROFILE: "/teachers/profile",
    UPLOAD_IMAGE: "/profile/upload-image",
    CHANGE_PASSWORD: "/profile/change-password",
    LOGOUT: "/teachers/logout",
  },
  SCHEDULE: {
    SESSIONS: "/teachers/sessions",
  },
  PRIVATE: {
    BOOKINGS: "/teachers/private-session-bookings",
    PENDING: "/teachers/private-session-bookings?status=pending_teacher&per_page=200",
    ACCEPTED: "/teachers/private-session-bookings?status=accepted&per_page=200",
    CANCELLED: "/teachers/private-session-bookings?status=cancelled&per_page=200",
    ACCEPT: (id: string | number) => `/teachers/private-session-bookings/${id}/accept`,
    REJECT: (id: string | number) => `/teachers/private-session-bookings/${id}/reject`,
    ONE_TO_ONE_PENDING: "/teachers/one-to-one/sessions?status=pending&per_page=100",
    ONE_TO_ONE_ACCEPTED: "/teachers/one-to-one/sessions?status=accepted&per_page=100",
    ONE_TO_ONE_CONFIRMED: "/teachers/one-to-one/sessions?status=confirmed&per_page=100",
    ONE_TO_ONE_CANCELLED: "/teachers/one-to-one/sessions?status=cancelled&per_page=100",
    ONE_TO_ONE_REJECTED: "/teachers/one-to-one/sessions?status=rejected&per_page=100",
    ONE_TO_ONE_ACCEPT: (id: string | number) => `/teachers/one-to-one/accept/${id}`,
    ONE_TO_ONE_REJECT: (id: string | number) => `/teachers/one-to-one/reject/${id}`,
    TRIAL_REQUESTS: "/teachers/trial-requests",
    TRIAL_MATCHED: "/teachers/trial-requests/matched",
    TRIAL_CANCELLED: "/teachers/trial-requests/cancelled",
    TRIAL_ACCEPT: (id: string | number) => `/teachers/trial-requests/${id}/accept`,
    TRIAL_DECLINE: (id: string | number) => `/teachers/trial-requests/${id}/decline`,
  },
  NOTIFICATIONS: {
    REGISTER_DEVICE: "/teachers/device/register",
    TEST_PUSH: "/teachers/notifications/test-push",
  },
  REVIEWS: {
    FEEDBACK: "/teachers/review/by/student",
    STUDENTS: "/teachers/review/student",
  },
  HALL: {
    LIST: "/teachers/link/teacher",
    CREATE: "/teachers/link/teacher",
    UPDATE: "/teachers/link/teacher/",
    DELETE: "/teachers/link/teacher/",
    TOGGLE: "/teachers/teacher/link/",
    CONNECT_LOGIN: "/teachers/connect/login",
  },
  GUIDES: {
    LIST: "/teachers/guides",
  },
  LIBRARY: {
    LOGIN_LINK: "/teachers/library/login-link",
    INFO: "/teachers/library/info",
  },
  GROUPS: {
    LIST: "/teachers/subject/groups",
    CREATE: "/teachers/groups",
    STUDENTS: "/teachers/groups/",
    DELETE: "/teachers/groups/",
    REVIEW: "/teachers/review/student/subject/",
  },
  PACKAGES: {
    LIST: "/teachers/groups/packages",
  },
  CONTENTS: {
    BY_SESSION: "/teachers/sessions/content/",
    ADD: "/teachers/sessions/content/upload-one",
    UPDATE: "teachers/sessions/content/",
    DELETE: "teachers/sessions/content/",
    RECORDINGS: "/teachers/sessions/recordings",
  },
} as const;
